version: '2.3'

services:

  mysqldb:
    image: ${DOCKER_REPOSITOR}/mysql:5.7
    container_name: mysqldb
    volumes:
    - ./mysqldb:/var/lib/mysql
    - ./config/my.cnf:/etc/my.cnf
    - ./init:/docker-entrypoint-initdb.d/
    - /etc/localtime:/etc/localtime:ro
    restart: always
    hostname: mysqldb
    environment:
    - SET_CONTAINER_TIMEZONE=true
    - TZ=Asia/ShangHai
    - MYSQL_ROOT_PASSWORD=duxue
    - MYSQL_DATABASE=duxue
    - MYSQL_USER=duxue
    - MYSQL_PASSWORD=duxue@365
    ports:
    - "3306:3306"

  duxue-manager:
    image: ${DOCKER_REPOSITOR}/duxue-manager:${VERSION}
    depends_on:
    - mysqldb
    container_name: duxue-manager
    restart: always
    environment:
    - MYSQL_HOST=${MYSQL_HOST}
    - DOMAIN=${DOMAIN}
    - TZ=Asia/Shanghai
    network_mode: "host"
    volumes:
    - /opt/log/yalun-manager:/home/duxue/logs
    - /opt/data/yalun-manager:/profile
    - /etc/localtime:/etc/localtime:ro

  duxue-api:
    image: ${DOCKER_REPOSITOR}/duxue-api:${VERSION}
    depends_on:
      - mysqldb
    container_name: duxue-api
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - TZ=Asia/Shanghai
    network_mode: "host"
    volumes:
      - /opt/log/yalun-api:/home/duxue-api/logs
      - /opt/data/yalun-manager:/profile
      - /etc/localtime:/etc/localtime:ro

